let burgerJson = [
    {id:1, name: 'Super Big Find', img:'images/burger5.png', price: 19.99, sizes: ['Pequena', 'Média', 'Grande'], description: 'Um clássico irresistível! Este hambúrguer suculento é coberto com queijo cheddar derretido e generosas fatias de bacon crocante. Complementado por alface fresca, tomate suculento e um toque de molho barbecue, tudo servido em um pão macio e tostado. Uma explosão de sabores em cada mordida.'},
    {id:2, name: 'Delicious Find', img:'images/burger2.png', price: 21.99, sizes: ['Pequena', 'Média', 'Grande'], description: 'Transporte seu paladar para o Mediterrâneo com este hambúrguer único. Feito com um suculento hambúrguer de cordeiro temperado, coberto com queijo feta cremoso, azeitonas pretas fatiadas, tomate cereja, alface crocante e um toque refrescante de molho tzatziki, tudo servido em um pão de hambúrguer levemente grelhado. Uma combinação deliciosa de sabores mediterrâneos.'},
    {id:3, name: 'Supreme Find', img:'images/burger3.png', price: 22.99, sizes: ['Pequena', 'Média', 'Grande'], description: 'Prepare-se para uma experiência cheia de sabor! Este hambúrguer suculento é coberto com queijo cheddar derretido, cebola roxa caramelizada e uma generosa porção de molho barbecue defumado. Finalizado com alface fresca, tomate maduro e um toque cremoso de molho ranch, tudo servido em um pão de hambúrguer tostado. Uma explosão de sabores que vai deixar você querendo mais.'},
    {id:4, name: 'Find Happiness ', img:'images/burger4.png', price: 17.99, sizes: ['Pequena', 'Média', 'Grande'],description: 'Uma opção saudável e deliciosa para os amantes de plantas. Este hambúrguer vegano é feito com uma base de quinoa temperada, grão-de-bico e legumes frescos, grelhados até a perfeição. Servido em um pão integral e acompanhado por alface crocante, tomate suculento e um toque de molho de tahine. Um hambúrguer que agrada a todos os paladares.'},
    {id:5, name: 'Find the Monster', img:'images/burger5.png', price: 25.99, sizes: ['Pequena', 'Média', 'Grande'],description: 'Uma combinação clássica que nunca decepciona. Este hambúrguer é coberto com queijo mozarela derretido, tomate fresco, manjericão perfumado e um toque de azeite de oliva extravirgem. Tudo isso servido em um pão artesanal levemente tostado. Uma opção leve, fresca e cheia de sabor.'},
    {id:6, name: 'Find Bacon', img:'images/burger6.png', price: 29.99, sizes: ['Pequena', 'Média', 'Grande'],description: 'Se você busca um pouco de tempero e picância, este hambúrguer é para você. Feito com um suculento hambúrguer de carne bovina temperada com especiarias cajun, coberto com queijo pepper jack derretido, cebola roxa fatiada, pimentão grelhado e um toque de molho picante. Servido em um pão de hambúrguer levemente grelhado. Prepare-se para uma explosão de sabores audaciosos.'},
    {id:7, name: 'Find Chesse Bacon', img:'images/burger7.png', price: 31.99, sizes: ['Pequena', 'Média', 'Grande'],description: 'Uma opção saborosa e exótica para os fãs de frango. Este hambúrguer é feito com uma suculenta carne de frango grelhada e coberto com um delicioso molho teriyaki. Complementado por fatias de abacaxi grelhado, alface fresca e maionese caseira, tudo servido em um pão de hambúrguer tostado. Uma combinação perfeita de doce e salgado.'},
    {id:8, name: 'Find Chicken', img:'images/burger8.png', price: 24.99, sizes: ['Pequena', 'Média', 'Grande'],description: 'Para os amantes de frutos do mar, este hambúrguer é uma escolha refrescante. Feito com um suculento filé de peixe grelhado, coberto com queijo feta cremoso, azeitonas pretas fatiadas, tomate cereja, alface crocante e um toque de molho tzatziki, tudo servido em um pão de hambúrguer levemente grelhado. Uma explosão de sabores mediterrâneos com um toque marítimo.'},
    {id:9, name: 'Find Children', img:'images/burger9.png', price: 28.99, sizes: ['Pequena', 'Média', 'Grande'],description: 'Uma opção sofisticada para os paladares exigentes. Este hambúrguer gourmet é feito com uma combinação de cogumelos Portobello e shiitake grelhados, cobertos com queijo brie derretido, rúcula fresca, cebola caramelizada e um toque de molho de trufas. Tudo isso servido em um pão artesanal levemente tostado. Uma experiência gastronômica única e saborosa.'},
]